version: '3'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/db
      - ./config/configdb
  
  mongo_seed:
    build:
      context: ./seed
    depends_on:
      - local
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    depends_on:
      - mongodb
          
  local:
    image: puleo/carwash-local
    ports:
      - "3001:8000"
    restart: always
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_HOST: mongodb
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: carwash_db
      DB_PORT: 27017
    depends_on:
      - mongodb